gitlab#3868 -- Implement /api/indexer/info in js-client
Lucas-Paganini-Programming/js-client pull request #5
Opened 2021-12-16 11:19 UTC by Puszkarek

2021-12-16 15:39 UTC, iagojsilva commented on package.json
> +		"decoders": "~1.22.2",
S: If this version is the only compatible with the project, remove the `~`

2021-12-16 15:40 UTC, iagojsilva commented on src/functions/indexers/get-all-indexers.spec.ts
> +	it(
S: Create another test: `Should return an empty array if there are no Indexers`

2021-12-16 15:40 UTC, iagojsilva commented on src/models/indexer/is-indexer-well.ts
> +		return isUUID(i.UUID) && isString(i.Name) && isArray(i.Wells) && isObject(i.Replicated);
```
const value = {
 UUID: 1,
 Name: 'well-name'
 Wells: ['i don't care what I am']
 Replicated: ['i'm an object too']
}
isIndexerWell(value) // returns true

```
M: Improve this check. Take a look at `is-saved-query.ts`

2021-12-16 15:41 UTC, iagojsilva commented on src/models/indexer/response-guard.ts
> +export const responseGuard = guard(indexerWellDecoder);
S: Move this to the same file of `indexerWellDecoder` to improve reading.

2021-12-16 16:16 UTC, Puszkarek commented on src/models/indexer/is-indexer-well.ts
> +		return isUUID(i.UUID) && isString(i.Name) && isArray(i.Wells) && isObject(i.Replicated);
tidy

2021-12-16 16:20 UTC, Puszkarek commented on src/functions/indexers/get-all-indexers.spec.ts
> +	it(
for that, it would not be necessary to have the `deleteOneIndexer` method? like in `get-all-groups.spec.ts`

2021-12-16 17:15 UTC, Puszkarek commented on src/models/indexer/response-guard.ts
> +export const responseGuard = guard(indexerWellDecoder);
tidy

2021-12-16 18:27 UTC, iagojsilva commented on package.json
> +		"decoders": "~1.22.2",
We don't know if they release a new minor version it'll break or not, I got you probably not, but remove the `~` for safety if we need we upgrade it manually

2021-12-16 18:28 UTC, iagojsilva commented on src/functions/indexers/get-all-indexers.spec.ts
> +	it(
ok

2021-12-16 18:28 UTC, iagojsilva commented on src/models/indexer/indexer-well.ts
> +export const isIndexerWell = (value: any): value is IndexerWell => {
S: Use `unknown` instead of `any`

2021-12-16 18:28 UTC, iagojsilva commented on src/models/indexer/replicated-state.ts
> +export const isReplicatedState = (value: any): value is ReplicatedState => {
S: Use `unknown` instead of `any`

2021-12-16 18:28 UTC, iagojsilva commented on src/models/indexer/shard.ts
> +export const isShard = (value: any): value is Shard => {
S: Use `unknown` instead of `any`

2021-12-16 18:28 UTC, iagojsilva commented on src/models/indexer/well.ts
> +export const isWell = (value: any): value is Well => {
S: Use `unknown` instead of `any`

2021-12-16 18:35 UTC, Puszkarek commented on src/models/indexer/shard.ts
> +export const isShard = (value: any): value is Shard => {
done

2021-12-16 18:35 UTC, Puszkarek commented on src/models/indexer/replicated-state.ts
> +export const isReplicatedState = (value: any): value is ReplicatedState => {
done

2021-12-16 18:35 UTC, Puszkarek commented on src/models/indexer/indexer-well.ts
> +export const isIndexerWell = (value: any): value is IndexerWell => {
done

2021-12-16 18:35 UTC, Puszkarek commented on src/models/indexer/response-guard.ts
> +export const responseGuard = guard(indexerWellDecoder);
done

2021-12-16 18:55 UTC, Puszkarek commented on src/models/indexer/well.ts
> +export const isWell = (value: any): value is Well => {
done

2021-12-17 16:43 UTC, LucasPaganini requested changes

2021-12-17 16:43 UTC, LucasPaganini commented on src/functions/indexers/get-all-indexers.ts
> +		const rawRes = (await parseJSONResponse<any>(raw)) ?? [];
M: Don't use `<any>`, use the correct expected type

2021-12-17 16:43 UTC, LucasPaganini commented on src/functions/indexers/get-all-indexers.spec.ts
> +import { makeGetAllIndexers } from '.';
M: Don't import from `'.'`, import from the actual file

2021-12-17 16:43 UTC, LucasPaganini commented on src/functions/indexers/get-all-indexers.spec.ts
> +		'Should return all IndexersWells',
S: Typo, `IndexersWells` should be `IndexerWells`. The `s` comes at the end.

2021-12-17 16:43 UTC, LucasPaganini commented on src/models/indexer/indexer-well.ts
> +export type IndexerWell = {
M: This is the `RawIndexerWell`. Create another interface, normalized, with better parameter names, to be the `IndexerWell`.

2021-12-17 16:43 UTC, LucasPaganini commented on src/models/indexer/replicated-state.ts
> +export interface ReplicatedState {
M: This is the `RawReplicatedState`. Create another interface, normalized, with better parameter names, to be the `ReplicatedState`.

2021-12-17 16:43 UTC, LucasPaganini commented on src/models/indexer/response-guard.spec.ts
> +import { responseGuard } from '.';
M: Don't import from `'.'`

2021-12-17 16:43 UTC, LucasPaganini commented on src/models/indexer/response-guard.ts
> +const shardDecoder = object({
S: Rename to `rawShardDecoder`

2021-12-17 16:43 UTC, LucasPaganini commented on src/models/indexer/response-guard.ts
> +const indexerWellDecoder = dict(
S: Rename to `rawIndexerWellDecoder`

2021-12-17 16:43 UTC, LucasPaganini commented on src/models/indexer/response-guard.ts
> +export const responseGuard = guard(indexerWellDecoder);
M: Rename to `assertIsRawIndexerWell`

2021-12-17 16:43 UTC, LucasPaganini commented on src/models/indexer/response-guard.spec.ts
> +fdescribe('responseGuard()', () => {
M: Don't `fdescribe`

2021-12-17 16:43 UTC, LucasPaganini commented on src/models/indexer/response-guard.spec.ts
> +	describe('Should work', () => {
M: Add a test for the function types. It should have the type `(data: unknown) => asserts data is RawIndexerWell`

2021-12-17 16:43 UTC, LucasPaganini commented on src/models/indexer/shard.ts
> +export type Shard = {
M: This is the `RawShard`. Create another interface, normalized, with better parameter names, to be the `Shard`.

2021-12-17 16:43 UTC, LucasPaganini commented on src/models/indexer/well.ts
> +export type Well = {
M: This is the `RawWell`. Create another interface, normalized, with better parameter names, to be the `Well`.

2021-12-17 17:33 UTC, Puszkarek commented on src/functions/indexers/get-all-indexers.ts
> +		const rawRes = (await parseJSONResponse<any>(raw)) ?? [];
tidy

2021-12-17 17:34 UTC, Puszkarek commented on src/functions/indexers/get-all-indexers.spec.ts
> +import { makeGetAllIndexers } from '.';
tidy

2021-12-17 17:35 UTC, Puszkarek commented on src/functions/indexers/get-all-indexers.spec.ts
> +		'Should return all IndexersWells',
tidy

2021-12-17 17:36 UTC, Puszkarek commented on src/models/indexer/indexer-well.ts
> +export type IndexerWell = {
I think that this is the IndexerWell and the RawIndexerWell is some like
```
export type RawIndexerWell = {
	[key: string]: Omit<IndexerWell, 'Name'>;
};
```

2021-12-17 17:46 UTC, Puszkarek commented on src/models/indexer/well.ts
> +export type Well = {
but this decoder also converts `iso8601` string from
const shardDecoder = object({
	Start: iso8601,
	End: iso8601,
	...
	),
to `Date`, I don't think that `asserts` would be the best option

2021-12-17 17:47 UTC, Puszkarek commented on src/models/indexer/response-guard.ts
> +export const responseGuard = guard(indexerWellDecoder);
but this decoder also converts `iso8601` string from
const shardDecoder = object({
	Start: iso8601,
	End: iso8601,
	...
	),
to `Date`, I don't think that `asserts` would be the best option

2021-12-17 17:57 UTC, Puszkarek commented on src/models/indexer/response-guard.ts
> +const shardDecoder = object({
tidy

2021-12-17 17:57 UTC, Puszkarek commented on src/models/indexer/response-guard.ts
> +const indexerWellDecoder = dict(
tidy

2021-12-17 17:57 UTC, Puszkarek commented on src/models/indexer/response-guard.spec.ts
> +import { responseGuard } from '.';
tidy

2021-12-17 18:08 UTC, Puszkarek commented on src/models/indexer/replicated-state.ts
> +export interface ReplicatedState {
tidy

2021-12-17 18:08 UTC, Puszkarek commented on src/models/indexer/response-guard.spec.ts
> +fdescribe('responseGuard()', () => {
tidy

2021-12-17 18:08 UTC, Puszkarek commented on src/models/indexer/shard.ts
> +export type Shard = {
tidy

2021-12-17 18:08 UTC, Puszkarek commented on src/models/indexer/well.ts
> +export type Well = {
tidy

2021-12-17 18:17 UTC, Puszkarek commented on src/models/indexer/response-guard.spec.ts
> +	describe('Should work', () => {
`asserts` is not compatible with typescript v3.5 and 3.6

2021-12-20 12:47 UTC, iagojsilva commented on src/models/indexer/shard.ts
> +};
S: Use camelCase in the normalized types

2021-12-20 12:48 UTC, iagojsilva commented on src/models/indexer/well.ts
> +};
S: Use camelCase in the normalized types

2021-12-20 12:49 UTC, iagojsilva commented on src/models/indexer/replicated-state.ts
> +export interface ReplicatedState {
S: Use camelCase in the normalized types

2021-12-20 16:49 UTC, iagojsilva commented on src/models/indexer/indexer-well.ts
> +	UUID: string;
M: use `uuid` instead of `UUID`

2021-12-20 16:49 UTC, iagojsilva commented on src/models/indexer/raw-indexer-well-decoder.ts
> +	UUID: string;
M: use uuid instead of UUID

2021-12-20 16:49 UTC, iagojsilva commented on src/models/indexer/raw-indexer-well.ts
> +		UUID: string;
M: use uuid instead of UUID

2021-12-20 16:57 UTC, iagojsilva commented on src/models/indexer/raw-replicated-state.ts
> +	Shards: Array<RawShardDecoded>;
S: Why this is `RawShardDecoded` and not `RawShard`

2021-12-20 17:04 UTC, iagojsilva commented on src/models/indexer/response-guard.spec.ts
> +const validMockData = () => {
S: Improve your mocks, make them strictly typed and there are too big there is no need to set all these props just set the required ones

2021-12-20 17:06 UTC, iagojsilva commented on src/models/indexer/response-guard.spec.ts
> +	const validEmpty = {};
S: I still don't get how an empty object could be valid data for a type whose props are all mandatory

2021-12-20 17:50 UTC, Puszkarek commented on src/models/indexer/response-guard.spec.ts
> +	const validEmpty = {};
because the object is inside a key `{[key: string]: Indexer}`

ex:
```
const valid = {}
const invalid = {
	'name-key': undefined
}
```
like an empty array

2021-12-20 17:54 UTC, Puszkarek commented on src/models/indexer/indexer-well.ts
> +	UUID: string;
tidy

2021-12-20 17:56 UTC, Puszkarek commented on src/models/indexer/raw-replicated-state.ts
> +	Shards: Array<RawShardDecoded>;
fixed

2021-12-20 19:34 UTC, Puszkarek commented on src/models/indexer/response-guard.spec.ts
> +const validMockData = () => {
I made some improvements to the mock, but most properties are required

2021-12-20 20:18 UTC, iagojsilva commented on src/models/indexer/response-guard.spec.ts
> +	const validEmpty = {};
If we send this data to the backend it'll accept that?

2021-12-21 11:20 UTC, Puszkarek commented on src/models/indexer/response-guard.spec.ts
> +	const validEmpty = {};
we don't send, it only has a `getAll`

2022-01-04 06:51 UTC, closed without merging